### ISSUE TITLE
Handling flipped/mirrored tiles

### ISSUE THREAD

**Issue by zilti** [oakes/tile-soup#2]
Adding a flipped and/or mirrored tile causes the encoded number to be too big for an int (e.g.: 2147483651), making tile-soup fail while parsing a tmx file.

On top of that, is it in or out of tile-soup's scope to decode the bitmask for flipping? See https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping.

**Comment by oakes** [comment]
Already supported :D

https://oakes.github.io/tile-soup/cljs/tile-soup.core/tile-id-'g'map.html

I'll check out your pr soon, thanks

**Comment by oakes** [comment]
I pushed 0.4.2 to clojars with your fix, thanks.
